### ISSUE TITLE
software package version for reproduction

### ISSUE THREAD

**Issue by oneway3124** [HanbaekLyu/ONMF-COVID19#3]
Hi Sir,

Can you supply the environment software package version for reproduce?

ONMF-COVID19) davwang@ubuntu:~/ONMF-COVID19$ python main.py 
pre-training temporal dictionary started...
Traceback (most recent call last):
  File "/home/davwang/ONMF-COVID19/main.py", line 264, in <module>
    main()
  File "/home/davwang/ONMF-COVID19/main.py", line 260, in main
    main_train_joint()
  File "/home/davwang/ONMF-COVID19/main.py", line 42, in main_train_joint
    reconstructor = ONMF_timeseries_reconstructor(path=path_COVID_tracking_proj,
TypeError: __init__() got an unexpected keyword argument 'state_list'

**Comment by oneway3124** [comment]
https://github.com/HanbaekLyu/ONMF-COVID19/
git clone https://github.com/CSSEGISandData/COVID-19
run main.py

conda create -n ONMF-COVID19
conda activae ONMF-COVID19
conda install numpy
conda install matplotlib
conda install -c tensorly tensorly
conda install -c anaconda scikit-learn
conda install pandas
conda install jupyter notebook

**Comment by oneway3124** [comment]
![20210402070349](https://user-images.githubusercontent.com/3787176/113362849-f1b27200-9381-11eb-8120-af3d58dbfed1.png)
![download1](https://user-images.githubusercontent.com/3787176/113362851-f2e39f00-9381-11eb-83a5-884a5c824ab2.png)

**Comment by oneway3124** [comment]
Hi Sir,

Can you supply some more detail information for this reproduction ?
I want to apply your model into other time series such as power forecasting and so on.
Thanks for your help in advance.

**Comment by HanbaekLyu** [comment]
Thanks a lot for your inquiry. I am currently working on revising the repository so that it is more easy to apply to non-covid datasets. I will update you once it's updated.

**Comment by oneway3124** [comment]
Thanks for your response!   Looking forward to your update.

**Comment by HanbaekLyu** [comment]
Please take a look at the new public repo: https://github.com/HanbaekLyu/TDL
It should have a cleaner implementation of our main algorithm for general purpose time-series data. Hope you find it useful.
